## Fichier : docker-compose.yml
version: '3.8'

services:
  gold_back:
    build:
      dockerfile: Dockerfile
    container_name: gold_back
    ports:
      - '3001:3000'
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
