###
POST http://localhost:3000/graphql
Content-Type: application/json
Authorization: Bearer token
X-REQUEST-TYPE: GraphQL

query {
  auth (
    dto: {
      login: "faro"
      password: "prout"
    }
  ) {
    accessToken
    id
    code
  }
}