###
POST {{host}}/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query {
  auth (
    dto: {
      login: "{{login}}"
      password: "{{password}}"
    }
  ) {
    accessToken
    id
    code
    name_first
    name_last
    description
    mail
    creation
    modification
    language
  }
}