###
POST {{host}}/graphql
Content-Type: application/json
Authorization: Bearer {{token}}
X-REQUEST-TYPE: GraphQL

query {
  users {
    id
    code
    name_first
    name_last
    description
    mail
    role
  }
}

###
POST {{host}}/graphql
Content-Type: application/json
Authorization: Bearer {{token}}
X-REQUEST-TYPE: GraphQL

query {
  user (
    dto: {
      id: "65d615385688080e0a0f0ec2"
      #code: "faro"
    }
  ) {
    id
    code
    name_first
    name_last
    description
    mail
    role
  }
}

###
POST {{host}}/graphql
Content-Type: application/json
Authorization: Bearer {{token}}
X-REQUEST-TYPE: GraphQL

mutation {
  create_user (
    dto: {
      code: "fitdesk"
      password: "bBh7LfB_"
      name_first: "Fitdesk"
      name_last: "Fitdesk"
      description: "Pour la trésorerie de Fitdesk"
      mail: "f.rosito.dreamteam@gmail.com"
    }
  ) {
    id
    code
    name_first
    name_last
    description
    mail
    role
  }
}
