/* istanbul ignore file */
export enum ERRORS {
  AUTH_PASSKEY_USECASE_FAIL = 'AUTH_PASSKEY_USECASE_FAIL',
  BDD_SERVICE_SQL_NO_FILTER = 'BDD_SERVICE_SQL_NO_FILTER',
  CREATE_PASSKEY_USECASE_FAIL = 'CREATE_PASSKEY_USECASE_FAIL',
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',
  OPERATION_NOT_FOUND = 'OPERATION_NOT_FOUND',
}
